spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lixue?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 300ms
      quiet-period: 299ms
  data:
    elasticsearch:
      cluster-name: lixue
      cluster-nodes: 123.207.11.229:9300
      repositories:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
server:
  servlet:
    context-path: /lixue
mybatis:
  type-aliases-package: xyh.lixue.searchProblem.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    xyh.lixue.searchProblem: debug