spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lixue?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
  data:
    elasticsearch:
      cluster-name: lixue
      cluster-nodes: 123.207.11.229:9300
      repositories:
        enabled: true
server:
  servlet:
    context-path: /searchlite
  port: 8080
mybatis:
  type-aliases-package: xyh.lixue.searchProblem.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    xyh.lixue.*: debug

ocr:
  api: https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic
wechat:
  url: https://api.weixin.qq.com/sns/jscode2session?appid=wx662ad8d7fca7be14&secret=5a809b950b7268df577d78404ad141c3&grant_type=authorization_code&js_code=
cos:
  uri: https://fuguangyu-1254071215.cos.ap-shanghai.myqcloud.com/problem/