spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.207.11.229:3306/search_lite?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yxyj6900@
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  data:
    elasticsearch:
      cluster-name: es-searchlite
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  kafka:
    listener:
      missing-topics-fatal: false
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: searchlite
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  servlet:
    context-path: /searchlite
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2.xml
  level:
    xyh.*.*: debug

ocr:
  api: https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic
wechat:
  url: https://api.weixin.qq.com/sns/jscode2session?appid=wx1fe598d24603a4ec&secret=7682399130d4967f8d99961fad02d064&grant_type=authorization_code&js_code=
cos:
  uri: https://fuguangyu-1254071215.cos.ap-shanghai.myqcloud.com/problem/